### ISSUE TITLE
Export in FireFox

### ISSUE THREAD

**Issue by realsmartnose** [calien666/typo3-xlsexport#1]
Firefox safe the file as xlsx
This is not correct, the file format is not openxmlformats

It would be great to have the content-type configurable or at least the correct mimetype:
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet -> application/vnd.ms-excel
After changing the header, the download and open works in Firefox too

**Comment by calien666** [comment]
Hello, thanks for your Issue report, version 2.1.1 and 3.0 will fix this issue and set the correct writer for xlsx filetypes
