### ISSUE TITLE
DBAL has no methode fetchAllAssociative()

### ISSUE THREAD

**Issue by realsmartnose** [calien666/typo3-xlsexport#2]
The DBAL delivered in 10.4.21 seems to be another version like the one from composer.
The one on life-systems does not have a method fetchAllAssociative and therefore the export does not work

If we change fetchAllAssociative() to fetchAll() it works without problems (but fetchAll is deprecated...)

![image](https://user-images.githubusercontent.com/40367827/139495741-318851db-9274-4cf0-adba-c3ffe8b13847.png)

Left: composer-version with fetchAllAssociative
Right: download-version without fetchAllAssociative

**Comment by calien666** [comment]
new Version 2.1.2 has this error fixed
