### ISSUE TITLE
Code share

### ISSUE THREAD

**Issue by klodeckl** [calien666/typo3-xlsexport#3]
This issue belongs to https://github.com/calien666/persisted-sanitized-routing/issues/4. But I am not able to post there again because you archived the repository but asked me to share the code.
So here it is: https://gist.github.com/klodeckl/08ab910b3ec6ef3e4acb2bed1c986406

It’s not optimal, path_segment and path_segment_en is currently hardcoded… have a look at it yourself.

**Comment by calien666** [comment]
Hey, @klodeckl. Please take a look into https://github.com/calien666/typo3-extended-routing, where there is this Mapper and some other additional mappers included now.
This decision was made, because the naming of this ext was not best for adding more Aspect mappers
