### ISSUE TITLE
render flexform in field

### ISSUE THREAD

**Issue by p-view** [calien666/typo3-xlsexport#4]
hello, is it possible to render Flexform fields to xls? 
is it possible to format the fields before exporting?
THX

**Comment by calien666** [comment]
Hi, the export of flexform was never tested, but should work.

Field formatting is not included, but you have three hooks, which could help you

https://github.com/calien666/typo3-xlsexport/blob/main/Classes/Traits/ExportWithTsSettingsTrait.php#L77
https://github.com/calien666/typo3-xlsexport/blob/main/Classes/Traits/ExportWithTsSettingsTrait.php#L99
https://github.com/calien666/typo3-xlsexport/blob/main/Classes/Traits/ExportTrait.php#L108

**Comment by calien666** [comment]
No interaction since a long time. Issue closed.
If you think, this is wrong, feel free, to open a new one.
