### ISSUE TITLE
Autoloader does not work under Linux

### ISSUE THREAD

**Issue by juergenfurrer** [calien666/typo3-xlsexport#6]
In case of case-sensitive file-system, the autoloading of PhpOffice\PhpSpreadsheet does not work.
To fix this, the autolaod in the composer.json has to be changed:

`  "autoload": {`
`    "psr-4": {`
`      "Calien\\Xlsexport\\": "Classes/",`
`      "PhpOffice\\PhpSpreadsheet\\": "vendor/phpoffice/phpspreadsheet/src/"`
`    }`
`  },`

**Comment by juergenfurrer** [comment]
Sorry, it does not load any of the required packages from the vendor folder, this is very strange, I can add the psr-4 config and it will work correctly, but in fact, my solution is not correct, this should work on the fly
I have some other extensions that uses required packages and it loads the dependencies correctly (on the same System)

I use PHP 8.1 and TYPO3 11.5.26

**Comment by calien666** [comment]
I'll take a look, as I don't understand actually, why the Autoloader doesn't work correct. Do you use TER version or composer installed version?

**Comment by juergenfurrer** [comment]
I use the TER version.
At the end, I used the following autoloader-config:
`  "autoload": {`
`    "psr-4": {`
`      "Calien\\Xlsexport\\": "Classes/",`
`      "PhpOffice\\PhpSpreadsheet\\": "vendor/phpoffice/phpspreadsheet/src/",`
`      "Psr\\SimpleCache\\": "vendor/psr/simple-cache/src/",`
`      "ZipStream\\": "vendor/maennchen/zipstream-php/src/",`
`      "MyCLabs\\": "vendor/myclabs/php-enum/src/"`
`    }`
`  },`
When I dont use this config, the classes from the vendor-folder are not in the `autoload_classmap.php`

**Comment by calien666** [comment]
Ok, I think, I found the original issue. Could you please try with original composer.json and change instead in ext_emconf.php:3
```php
$EM_CONF['xlsexport'] = [
```
to
```php
$EM_CONF[$_EXTKEY] = [
```

I guess, I have a problem in restrictions from TER, which forces using $_EXTKEY instead of string or constant there.

**Comment by juergenfurrer** [comment]
This is interesting, the ext_emconf.php looks different then the one in the repository...
`$EM_CONF[$_EXTKEY] = array (`
`  'title' => 'Calien - XLS Exporter',`
`  'description' => 'Excel exporter, fully configurable for every table',`
`  'category' => 'module',`
`  'version' => '3.1.0',`
`  'state' => 'beta',`
`  'uploadfolder' => false,`
`  'clearcacheonload' => false,`
`  'author' => 'Markus Hofmann & Frank Berger',`
`  'author_email' => 'typo3@calien.de',`
`  'author_company' => '',`
`  'constraints' => `
`  array (`
`    'depends' => `
`    array (`
`      'typo3' => '11.5.0-11.5.99',`
`    ),`
`    'conflicts' => `
`    array (`
`    ),`
`    'suggests' => `
`    array (`
`    ),`
`  ),`
`);`

**Comment by calien666** [comment]
the issue could be, that syntax is wrong. I'll fix this and will release a new minor

**Comment by juergenfurrer** [comment]
And therefor, I can not do the change.
Can it be, that TYPO3 is converting your emconf?

I just downloaded the zip-file from the TER, and inside the package, the emconf is identically to the one in the repository

**Comment by calien666** [comment]
New version release is online on [extensions.typo3.org/](https://extensions.typo3.org/extension/xlsexport). Downloaded the current version and autoload in ext_emconf is complete, as expected. Hope, this helps

**Comment by juergenfurrer** [comment]
The new version does not work, but I figured out, what the problem is...
Theres a wrong path in ext_emconf.php

Change this:
`'PhpOffice\\PhpSpreadsheet\\' => 'vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet',`

To this:
`'PhpOffice\\PhpSpreadsheet\\' => 'vendor/phpoffice/phpspreadsheet/src',`

When I change this before installing the EXT, it will work normally

**Comment by calien666** [comment]
Okay, thanks for the hint. I'll fix this asap and will release new minor.
